### ISSUE TITLE
NGINX not utilising embedded dns server in docker user defined network

### ISSUE THREAD

**Issue by jemcgrath1** [linuxserver/docker-muximux#10]
Running the linuxserver/docker-muximux container in docker 1.11.2,  NGINX does not use the embedded DNS server for a user defined network.

From the host OS, all other containers can be pinged by hostname and alias and fqdn successfully, however within muximux configuration only IP addresses work.
(External DNS works OK), the embedded DNS does not appear to be used.

Please advise how to correctly configure and or update the image so that the embedded DNS can be used to resolve containers by container name and/or alias.

**Comment by sparklyballs** [comment]
i'd advise updating docker on the host machine

then read this link for instructions on docker networking

https://docs.docker.com/engine/userguide/networking/

this would appear to be a docker problem rather than anything specific to this particular image so i'm closing this
