### ISSUE TITLE
Settings.ini.php Error

### ISSUE THREAD

**Issue by Shadow229** [linuxserver/docker-muximux#24]
Something is changing the settings.ini.php file making muximux not load through localhost.

After refreshing the webpage and muximux not loading I checked the nginx error log and get various errors - some examples below:

`2020/10/04 15:55:49 [error] 341#341: *713 FastCGI sent in stderr: "PHP message: PHP Warning:  syntax error, unexpected '"' in settings.ini.php on line 71`

`2020/10/04 15:54:25 [error] 340#340: *670 FastCGI sent in stderr: "PHP message: PHP Warning:  syntax error, unexpected BOOL_TRUE in settings.ini.php on line 16`

Most of the time its these, with the line in question being different depending on where the change has happened.

for example, this one just happened:

`2020/10/04 16:47:35 [error] 340#340: *822 FastCGI sent in stderr: "PHP message: PHP Warning:  syntax error, unexpected '"' in settings.ini.php on line 47`

when checking in the setting file, it looks like its randomly added an extra start to an object for portainer in there:

`[Plex]
name = "Plex"
url = "http://localhost:32400/web/index.html"
scale = 1
icon = "muximux-plex"
color = 1
icon = "muximux-plex"
color = "#f9be03"
enabled = "true"
default = "true"

[Portainer]
namefault = "true"

[Portainer]
namealhost:9000/#/home"
scale = 1
icon = "muximux-important_devices"
color = "#1a1bfe"
enabled = "true"`

Removing that allows it to work again, but its different things every time. Sometimes its too jumbled to bother working out what should / shouldn't be there so I've just got a working backup of it and keep swapping out it for the one that works - but its annoying having to do this quite frequently when trying to use it.

Searching for the same issue I think it looks like this has been closed before because it can't be replicated - but its definitely an issue for me.

Thanks

**Comment by aptalca** [comment]
That's most certainly a muximux issue rather than a docker one. You should report it upstream. We only package their app in a docker image.

**Comment by Shadow229** [comment]
Thanks for getting back to me @aptalca. I've reported this directly to mescon/muximux. For anyone looking for an answer to this - that report is [here](https://github.com/mescon/Muximux/issues/195)
