### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by kmlucy** [linuxserver/docker-muximux#3]
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)](https://linuxserver.io)

I am getting a 500 error from my Muximux container. It was working fine yesterday, and as far as I know, nothing changed. 

Host OS: Debian
Docker run command: 

```
docker run --name=muximux -v /etc/localtime:/etc/localtime:ro -v /opt/muximux:/config -e PGID=1000 -e PUID=1000 -p 8080:80 linuxserver/muximux
```

Docker log output:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/index.php/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-install: executing...
[cont-init.d] 40-install: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by sparklyballs** [comment]
on muximux itself or one of the panes in muximux ?

**Comment by kmlucy** [comment]
This is on muximux itself. I can manually get to each pane without issue.

**Comment by kmlucy** [comment]
I'm not sure what happened, but it appears my config somehow got corrupted. I wiped my config folder and everything is back up.

**Comment by sparklyballs** [comment]
shall i called this closed ?

**Comment by kmlucy** [comment]
Sure. I will reopen if the problem reoccurs.

**Comment by matthewdias** [comment]
This happened to me today. config became some php gibberish. unfortunately i didn't think to save the corrupted file but I seem to remember something indicating a permission error. If it happens again I will post it here.
