### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by tscibilia** [linuxserver/docker-muximux#7]
I'm having an issue which appears to be related to the permissions. when i run the muximux docker container i get an error in the stdout logs "[cont-init.d] 40-install: exited 1." as well as in the stderr log which indicates it can't chown the files in the config directory (see below). 

I'm running docker on an ubuntu xenial vm as the user tscibilia (uid 1000), i mapped the network drives to my synology box via fstab (i'm not sure what uid i have on synology or if that matters). 

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##Host OS##
tscibilia@Xenial-VM:/~$ uname -a
Linux Xenial-VM 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

##Command line users, your run/create command.##
sudo docker create \
--name=muximux \
-v /mnt/tscibilia/docker/muximux/:/config \
-e PGID=1000 -e PUID=1000 \
-e TZ=America/New_York \
-p 3001:80 \
--restart="always" \
linuxserver/muximux

##Docker log output, docker log muximux stdout log##

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/

GID/UID

User uid:    1000
User gid:    1000

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-install: executing... 
[cont-init.d] 40-install: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

##Docker log output, docker log muximux stderr log##
2017-03-09T16:17:54.073892316Z usermod: no changes
2017-03-09T16:17:54.332936209Z chown: changing ownership of '/config': Permission denied
2017-03-09T16:17:54.714488942Z chown: changing ownership of '/config/www/muximux': Permission denied
2017-03-09T16:17:54.714805394Z chown: changing ownership of '/config/www': Permission denied

##Mention if you're using symlinks on any of the volume mounts.##
tscibilia@Xenial-VM:/mnt$ ls -l
total 0
drwxrwxrwx 1 1024 users 0 Mar 9 12:33 Media
drwxrwxrwx 1 1024 root  0 Mar 9 12:30 tscibilia

tscibilia@Xenial-VM:/~$ id tscibilia
uid=1000(tscibilia) gid=1000(tscibilia) groups=1000(tscibilia),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),113(lpadmin),128(sambashare)

**Comment by sparklyballs** [comment]
> (i'm not sure what uid i have on synology or if that matters)

It absolutely matters, the "error" is solely down to not having permissions on the mounted volume on the synology

**Comment by ghost** [comment]
I'm seeing something similar... I have GUID and UID setup correctly (works in other containers) but `log` is not accessible and thus the process fails to start.

```bash
root@ef81d2aff9b9:/$ ls -al config/log/
ls: cannot access 'config/log/nginx': Permission denied
ls: cannot access 'config/log/php': Permission denied
total 0
drw-r--r-- 4 abc dialout 136 Apr 13 11:21 .
drwxr-xr-x 8 abc dialout 272 Apr 13 11:21 ..
d????????? ? ?   ?         ?            ? nginx
d????????? ? ?   ?         ?            ? php
```

In the logs I see this:

```bash
[13-Apr-2017 09:22:01] ERROR: failed to post process the configuration
[13-Apr-2017 09:22:01] ERROR: FPM initialization failed
nginx: [emerg] open() "/config/log/nginx/access.log" failed (13: Permission denied)
nginx: [emerg] open() "/config/log/nginx/access.log" failed (13: Permission denied)
[13-Apr-2017 09:22:02] ERROR: failed to open error_log (/config/log/php/error.log): Permission denied (13)
```

**Comment by j0nnymoe** [comment]
@usharf Could you supply your docker run command and also host OS info? Thanks
